"""Offline evidence checks for the bounded Pro-helper smoke, not model grading."""
import hashlib
import json
from pathlib import PurePosixPath


MARKER_PATH = "/mnt/data/checkpoints/smoke-marker.txt"


def assess_recovery(files, metadata, publisher, checkpoint_path, result_path, *, capture_receipts=()):
    """Use only harness receipts, never receipt-shaped data supplied by a helper.

    Each capture_receipts entry binds a publisher to a HelperSandbox.checkpoint
    result. Immutable content metadata remains valid for older smoke artifacts.
    """
    failed, unknown = [], []

    def valid_provenance(provenance):
        return (isinstance(provenance, dict) and provenance.get("kind") == "sandbox_file"
                and all(isinstance(provenance.get(k), str) and provenance[k]
                        for k in ("container_id", "file_id", "call_id", "sandbox_path")))

    def owned_path(path):
        return (isinstance(path, str) and path.startswith(publisher + "/")
                and "\\" not in path and str(PurePosixPath(path)) == path
                and not any(part.startswith(".") for part in PurePosixPath(path).parts))

    def downloaded(path):
        body = files.get(path)
        meta = metadata.get(path, {})
        provenance = meta.get("provenance", {})
        if not isinstance(provenance, dict):
            provenance = {}
        if not isinstance(body, str):
            unknown.append("missing artifact: " + path)
            return None, provenance
        if (not valid_provenance(provenance)
                or meta.get("source") != publisher or not owned_path(path)):
            unknown.append("missing direct-download provenance: " + path)
        if meta.get("sha256") != hashlib.sha256(body.encode("utf-8")).hexdigest():
            failed.append("artifact hash mismatch: " + path)
        return body, provenance

    cp_body, cp_source = downloaded(checkpoint_path)
    result_body, result_source = downloaded(result_path)
    try:
        cp, result = json.loads(cp_body), json.loads(result_body)
        if not isinstance(cp, dict) or not isinstance(result, dict):
            raise ValueError("expected objects")
    except (TypeError, ValueError):
        return {"status": "failed" if failed else "unverified", "errors": failed + unknown + ["missing or invalid checkpoint/result JSON"]}
    if any(item.get("protocol_failure") or item.get("original_nonce_verified") is False
           for item in (cp, result)):
        failed.append("helper explicitly reported a protocol/provenance failure")
    nonce = cp.get("nonce")
    if not isinstance(nonce, str) or len(nonce) != 32 or any(c not in "0123456789abcdef" for c in nonce):
        failed.append("invalid original nonce")
    if result.get("nonce") != nonce or result.get("restored_nonce") != nonce:
        failed.append("checkpoint/result nonce mismatch")

    # Receipts are generated by the downloader, never accepted from tool arguments.
    for source, label in ((cp_source, "original"), (result_source, "recovered")):
        if not valid_provenance(source):
            unknown.append(label + " artifact lacks valid provenance")
            continue
        candidates = [path for path, meta in metadata.items()
                      if path.startswith(publisher + "/checkpoints/")
                      and meta.get("source") == publisher
                      and valid_provenance(meta.get("provenance"))
                      and meta.get("provenance", {}).get("container_id") == source.get("container_id")
                      and meta.get("provenance", {}).get("call_id") == source.get("call_id")
                      and meta.get("provenance", {}).get("sandbox_path") == MARKER_PATH]
        found = bool(candidates)
        for path in candidates:
            body, _ = downloaded(path)
            if body is not None and body != nonce:
                failed.append(label + " sandbox marker differs from original checkpoint")

        # Deduplicated bytes keep their first provenance; a fresh capture receipt
        # proves the same bytes were downloaded at a later execution boundary.
        for receipt in capture_receipts:
            if not isinstance(receipt, dict):
                unknown.append("malformed capture receipt")
                continue
            if receipt.get("publisher") != publisher:
                continue
            boundary = receipt.get("checkpoint")
            if not isinstance(boundary, dict):
                unknown.append("malformed checkpoint boundary")
                continue
            if (boundary.get("source_container_id") != source["container_id"]
                    or boundary.get("source_call_id") != source["call_id"]):
                continue
            if boundary.get("status") != "passed" or boundary.get("errors") != []:
                failed.append(label + " checkpoint boundary did not pass")
                continue
            captured = boundary.get("captured")
            if not isinstance(captured, list):
                unknown.append(label + " checkpoint lacks fresh captures")
                continue
            for entry in captured:
                if not isinstance(entry, dict) or entry.get("sandbox_path") != MARKER_PATH:
                    continue
                path, provenance = entry.get("artifact_path"), entry.get("provenance")
                if (not owned_path(path) or not path.startswith(publisher + "/checkpoints/")
                        or not valid_provenance(provenance)
                        or provenance["sandbox_path"] != MARKER_PATH
                        or provenance["container_id"] != source["container_id"]
                        or provenance["call_id"] != source["call_id"]):
                    unknown.append(label + " capture has invalid ownership or provenance")
                    continue
                body, stored_provenance = downloaded(path)
                if body is None:
                    continue
                if (not valid_provenance(stored_provenance)
                        or stored_provenance["sandbox_path"] != MARKER_PATH):
                    unknown.append(label + " capture does not reference a downloaded marker")
                    continue
                encoded = body.encode("utf-8")
                if (entry.get("sha256") != hashlib.sha256(encoded).hexdigest()
                        or type(entry.get("bytes")) is not int or entry["bytes"] != len(encoded)):
                    failed.append(label + " capture hash or byte count mismatch")
                if body != nonce:
                    failed.append(label + " sandbox marker differs from original checkpoint")
                found = True
        if not found:
            unknown.append(label + " marker was not independently downloaded")
    if cp_source.get("container_id") == result_source.get("container_id"):
        unknown.append("fresh-sandbox recovery was not demonstrated")
    return {"status": "failed" if failed else "unverified" if unknown else "passed",
            "errors": failed + unknown}
